name: ✨ Feature Request
description: Suggest an idea for this project
title: "[FEATURE]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please fill out the form below to help us understand your request.

  - type: textarea
    id: feature-description
    attributes:
      label: ✨ Feature Description
      description: A clear and concise description of the feature you'd like to see implemented.
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: 🎯 Problem Statement
      description: What problem does this feature solve? What need does it address?
      placeholder: Describe the problem or need...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: 💡 Proposed Solution
      description: Describe your proposed solution or how you envision this feature working.
      placeholder: Describe your solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives Considered
      description: Describe any alternative solutions or features you've considered.

  - type: dropdown
    id: feature-type
    attributes:
      label: 📂 Feature Category
      description: What type of feature is this?
      options:
        - UI/UX Enhancement
        - Testing Improvement
        - Performance Optimization
        - Documentation
        - Developer Experience
        - User Experience
        - Security
        - Other
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: ✅ Acceptance Criteria
      description: What would make this feature complete? List the specific requirements.
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Context
      description: Add any other context, mockups, or screenshots about the feature request here.
      render: file

  - type: checkboxes
    id: feature-checklist
    attributes:
      label: 🧪 Feature Request Checklist
      description: Please confirm you've completed these steps
      options:
        - label: I have searched for existing feature requests before creating this one
          required: true
        - label: I have provided clear acceptance criteria
          required: true
        - label: I have considered the impact on existing functionality
          required: true
